import os

# BOT CONFIGURATION
BOT_TOKEN = os.getenv("BOT_TOKEN", "YOUR_BOT_TOKEN_HERE")
ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD", "secure123")

# GOOGLE SHEETS CONFIGURATION
GOOGLE_SHEETS_CREDENTIALS_FILE = "credentials.json"
SPREADSHEET_NAME = "ECommerce_Orders"
SHEET_NAME = "Orders"
SPREADSHEET_ID = "YOUR_SPREADSHEET_ID_HERE"

# SYSTEM SETTINGS
REPORT_TIME = "18:00"
TIMEZONE = "UTC"

# ACCESS CONTROL
ADMIN_ID = 123456789 
EMPLOYEE_IDS = [123456789]
